### ISSUE TITLE
Parse ei35

### ISSUE THREAD

**Issue by jakobsarthur** [OASES-project/ensemble#16]
Parse ei35

**Comment by jakobsarthur** [comment]
I parsed the unlinked data into SUTs, using GMB's parser. This does not remove the markets yet. 
Not sure what the sharing medium would be. The issue is also now linked to issue #20 I suppose?!

**Comment by jakobsarthur** [comment]
The issue is also now linked to issue #20 I suppose?! @cmutel?

**Comment by cmutel** [comment]
Closing for now; Ocelot has a parser that works OK and can be adapted to provide the information we need, and we need Ocelot in any case for system models.
