### ISSUE TITLE
Matching between industries and products in exiobase

### ISSUE THREAD

**Issue by aleksandra-kim** [OASES-project/ensemble#21]
As Stefan told me, the simplest way to obtain A matrix from the exiobase supply and use tables is to use the commodity technology construct. For that, some of the products need to be aggregated so that the matrices U and V become square. I started doing the matching between industries and products (see attached) and would be grateful if someone could fill in the gaps marked in blue.
[industries and products.pdf](https://github.com/OASES-project/ensemble/files/2415744/industries.and.products.pdf)

**Comment by stefanpauliuk** [comment]
Hi Sasha,

thanks for raising this issue! Please use the official 200->163 aggregation table of the EXIOBASE project, which is very close/identical to what you have anyway! See column T on sheet 'EXIOBASE3_pxi' file in 
\Dropbox\OASES\Data\EXIOBASE\EB4_Resolution
also shared here:
[EB4_Resolution.xlsx](https://github.com/OASES-project/ensemble/files/2419393/EB4_Resolution.xlsx)

I have more background info/metadata/correspondence tables available and the like. Don't hesitate to ask, could save you some working time each time!
